### ISSUE TITLE
Failed to import AWS resources

### ISSUE THREAD

**Issue by kayman-mk** [kishaningithub/tf-import-gen#34]
Great tool, it saved my day! However I found problems importing some resources.

Resources which can't be imported and shouldn't appear in the output:
- `aws_acm_certificate_validation`
- `aws_ami_copy`

`random_password` shouldn't be imported as it would reveal the password. Seems that the current logic doesn't cause any harm, but I think it is better to remove it too:
```hcl
import {
      to = random_password.rds_master_password
      id = "none"
    }
```

Resources which uses the wrong `id`. Terraform fails on import:
- `aws_ecs_cluster`: use the `name`
- `aws_ecs_task_definition`: use the `arn`
- `aws_wafv2_web_acl`: use `id/name/scope` from state file. Scope seems to be part of the `arn`: 6th field (until the first `/`)
- `aws_ecs_service`: use cluster_name/service_name from the `id` (last 2 fields separated by `/ `)
- `aws_autoscaling_schedule`: use `autoscaling_group_name/scheduled_action_name`
- `aws_appautoscaling_target`: use `service_namespace/id/scalable_dimension`
- `aws_appautoscaling_policy`: use `service_namespace/resource_id/scalable_dimension/name`

**Comment by kishaningithub** [comment]
Thanks a lot for submitting an issue with great detail ! Much appreciated! ☺️ 

Will definitely look into this! 👍

**Comment by kishaningithub** [comment]
@kayman-mk Have released a new version (v0.13.1) of go releaser. Do upgrade to the latest and let me know if it addressed all your observations/concerns.

**Comment by kayman-mk** [comment]
Great, thanks a lot.

Yes, the main concern was checking in the password by accident AS we run Terraform in our pipelines only. TfSec et al. Run in the pipeline, but that's of course too late.

**Comment by kishaningithub** [comment]
Have you tried trufflehog or talisman ?

We use that to stop the builds if someone checks on secret knowingly or unknowingly 

The best part is these 2 go through the commit history so people can't cheat by reverting a commit.
